sudo: required
dist: trusty

language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0

before_script:
    - composer self-update || true
    - composer install

script:
    - vendor/bin/phpunit

branches:
    only:
        - master
